exclude: "^$|deploy|scripts|tmp|{{cookiecutter.project_slug}}"
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
  - id: end-of-file-fixer
    exclude: "requirements*.txt"
  - id: check-toml
  # - id: debug-statements
  #   args: ["--print-changes"]

- repo: https://github.com/python-poetry/poetry
  rev: "1.7.1"
  hooks:
  - id: poetry-check
  - id: poetry-lock
    args:
    - --no-update
  - id: poetry-export
    args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
  - id: poetry-export
    name: poeetry-export-dev
    args: ["--with=dev", "-f", "requirements.txt", "-o", "requirements-dev.txt", "--without-hashes"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.6
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
