# .github/ISSUE_TEMPLATE/issue.yml
name: Issue
description: A new issue
title: " issue title"
projects:
  - vino9net/1
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Urgent
        - High
        - Low
      default: 2

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Why is this feature needed?
      placeholder: Describe the use case or user need.
