import json
import os
import shutil
import subprocess

context = json.loads(
    """
{{ cookiecutter | jsonify }}
"""
)

dockerfile_option = context["dockerfile_option"]

if dockerfile_option == "None":
    # none
    shutil.rmtree(".github")
    os.unlink("Dockerfile")
    os.unlink(".dockerignore")
elif dockerfile_option == "Dockerfile only":
    # dockerfile, no github workflow
    shutil.rmtree(".github")
else:
    # dockerfile and github workflow
    print(
        """
    Github workflow has been generated under .github/workflows directory. To create the corresponding
    Github repository, please run the following command:

        gh repo create {{ cookiecutter.project_slug }} --source=. --public

    Please ensure the workflow permission is seting to 'Read and write permissions' to enable pushing
    container images to Github container registry.

    """
    )

# create a git repo, everybody needs this, right?
subprocess.call(["git", "init"])
subprocess.call(["git", "add", ".gitignore", ".flake8"])
subprocess.call(["git", "add", "*"])
subprocess.call(["git", "commit", "-m", "generated by cookiecutter"])

# print some help messages
home = os.path.expanduser("~")
relpath = os.path.relpath(os.getcwd(), home)
print(
    f"""
# To start working on the project,

cd ~/{relpath}
poetry install
poetry run pre-commit install
poetry run isort **/*.py
poetry run black .
poetry shell


#    Hack away!

"""
)
