# run build and unit test to ensure the template is in working condition

on:
  push:
    branches:
    - develop
    - main

  pull_request:
    branches:
    - develop
    types: [opened, edited, reopened]

  workflow_dispatch:

jobs:
  python-test-and-build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Linting
      if: success()
      run: |
        flake8 --count --show-source --statistics

    # poetry and git are used when running
    # the unit tests, so we need to install
    # and configure them properly
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.6.1
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Configure Git
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"

    - name: Unit tests
      run: |
        pytest -v -s
